#!/usr/bin/env python

"""
Config settings for Pika and RabbitMQ
"""

QUEUE_HOST = 'YOUR_HOST_HERE'
QUEUE_MONITOR_INTERVAL = 5000
QUEUE_RETRY_DELAY = 5000
QUEUE_NAME = 'YOUR_NAME_HERE'
QUEUE_DURABLE = True
QUEUE_PREFETCH_COUNT = 1
QUEUE_NUM_RETRIES = 5
QUEUE_CONNECTION_ATTEMPTS = 5
